name: effora
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.3.0
  uuid: ^4.5.1
  flutter_slidable: ^4.0.0
  intl: ^0.20.2
  fl_chart: ^0.71.0
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  app_links: ^6.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/default_avatar.png
    - assets/logos/effora_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/effora_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/effora_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
